### ISSUE TITLE
[BUG] Error on JDA

### ISSUE THREAD

**Issue by dol4iua** [FabioZumbi12/UltimateChat#379]
After updating to 1.21.1, JDA does not start and gives an error

**Screenshots and LOGs**
[04:10:16] [Craft Scheduler Thread - 28 - UltimateChat/WARN]: [UltimateChat] Plugin UltimateChat v1.9.3-SNAPSHOT generated an exception while executing task 152
java.lang.NoClassDefFoundError: gnu/trove/map/TLongObjectMap
	at UltimateChat-JDA.jar/jdalib.jda.internal.utils.Checks.notEmpty(Checks.java:93) ~[UltimateChat-JDA.jar:?]
	at UltimateChat-JDA.jar/jdalib.jda.internal.utils.config.AuthorizationConfig.<init>(AuthorizationConfig.java:29) ~[UltimateChat-JDA.jar:?]
	at UltimateChat-JDA.jar/jdalib.jda.api.JDABuilder.build(JDABuilder.java:1816) ~[UltimateChat-JDA.jar:?]
	at UltimateChat-1.9.3-SNAPSHOT-b305-Universal (1).jar/br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscord.<init>(UCDiscord.java:73) ~[UltimateChat-1.9.3-SNAPSHOT-b305-Universal (1).jar:?]
	at UltimateChat-1.9.3-SNAPSHOT-b305-Universal (1).jar/br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.lambda$registerJDA$1(UChat.java:249) ~[UltimateChat-1.9.3-SNAPSHOT-b305-Universal (1).jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2291-bba87bf]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: gnu.trove.map.TLongObjectMap
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 11 more

**Server and plugins versions (please complete the following information):**
 - Server: [e.g. Purpur 1.21.1,]
 - Plugin Version: [e.g. UltimateChat-1.9.3-b305-Universal.jar]
 - Java Version: [e.g. Java 1.21]

**Comment by FabioZumbi12** [comment]
Please, use the release 1.9.2 only for now. I need to investigate 👀
